apiVersion: v1
kind: Service
metadata:
  name: nginx-lab
  namespace: configmap-lab
  labels:
    app: nginx-lab
spec:
  selector:
    app: nginx-lab
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
