apiVersion: v1
kind: Service
metadata:
  name: {{ include "configmap-volume-demo.fullname" . }}
  labels:
{{ include "configmap-volume-demo.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/name: {{ include "configmap-volume-demo.name" . | quote }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
