apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lab
  namespace: configmap-lab
  labels:
    app: nginx-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-lab
  template:
    metadata:
      labels:
        app: nginx-lab
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          envFrom:
            - configMapRef:
                name: web-ui-config
          command: ["/bin/sh", "-c"]
          args:
            - |
              cat <<EOF >/usr/share/nginx/html/index.html
              <!doctype html>
              <html lang="en">
                <head>
                  <meta charset="utf-8">
                  <title>ConfigMap EnvVar Demo</title>
                  <link rel="preconnect" href="https://fonts.googleapis.com">
                  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
                  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
                  <style>
                    body { font-family: 'Inter', sans-serif; background:#0f172a; color:#e2e8f0; margin:0; display:flex; justify-content:center; align-items:center; min-height:100vh; }
                    main { background:#1e293b; padding:3rem; border-radius:1rem; box-shadow:0 20px 45px rgba(15,23,42,.45); max-width:580px; }
                    h1 { font-size:2rem; margin-bottom:1rem; }
                    p { line-height:1.6; }
                    a { color:#38bdf8; font-weight:600; }
                    footer { margin-top:2rem; font-size:.85rem; color:#94a3b8; }
                    code { background:rgba(148,163,184,.2); padding:.2rem .4rem; border-radius:.35rem; }
                  </style>
                </head>
                <body>
                  <main>
                    <h1>${WELCOME_MESSAGE}</h1>
                    <p>This page lives inside an <code>nginx</code> container. The big headline above is sourced from a ConfigMap and injected as an environment variable.</p>
                    <p><a href="${LINK_URL}" target="_blank" rel="noopener">${LINK_TEXT}</a></p>
                    <footer>Try changing values inside <code>manifests/02-env-configmap/configmap.yaml</code> and reapplying them. The pod has to restart to pick up new env vars.</footer>
                  </main>
                </body>
              </html>
              EOF
              nginx -g "daemon off;"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
