apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lab
  namespace: configmap-lab
  labels:
    app: nginx-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-lab
  template:
    metadata:
      labels:
        app: nginx-lab
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          envFrom:
            - configMapRef:
                name: web-ui-config
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: web-ui-secrets
                  key: api-token
          volumeMounts:
            - name: web-ui-files
              mountPath: /usr/share/nginx/html
            - name: runtime-secret
              mountPath: /runtime
              readOnly: true
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: web-ui-files
          configMap:
            name: web-ui-files
        - name: runtime-secret
          secret:
            secretName: web-ui-secrets
            items:
              - key: api-token
                path: api-token.txt
