apiVersion: v1
kind: ConfigMap
metadata:
  name: web-ui-config
  namespace: configmap-lab
data:
  WELCOME_MESSAGE: "Welcome to the ConfigMap & Volume lab!"
  LINK_TEXT: "Open the Kubernetes docs"
  LINK_URL: "https://kubernetes.io/docs/concepts/storage/volumes/#configmap"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-ui-files
  namespace: configmap-lab
data:
  index.html: |
    <!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>ConfigMap Volume Demo</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
        <style>
          :root { color-scheme: light dark; }
          body { font-family: 'Inter', sans-serif; background:#0f172a; color:#e2e8f0; margin:0; padding:0; min-height:100vh; display:flex; align-items:center; justify-content:center; }
          main { background:#1e293b; padding:3rem; border-radius:1rem; box-shadow:0 30px 60px rgba(15,23,42,.55); max-width:700px; width:90%; }
          h1 { font-size:2.25rem; margin-bottom:1rem; }
          p { line-height:1.7; margin-bottom:1rem; }
          .panel { background:rgba(15,118,110,.2); border-left:4px solid #0f766e; padding:1rem; border-radius:.75rem; margin-top:2rem; }
          code { background:rgba(148,163,184,.2); padding:.2rem .45rem; border-radius:.35rem; }
          footer { margin-top:2rem; font-size:.85rem; color:#94a3b8; }
          .bubble { background:rgba(59,130,246,.18); border-radius:2rem; padding:.75rem 1.25rem; display:inline-block; margin-top:.5rem; }
        </style>
      </head>
      <body>
        <main>
          <h1 id="headline">Loading headline...</h1>
          <p id="blurb"></p>
          <div class="panel">
            <strong>Live ConfigMap Volume</strong>
            <p id="panelCopy"></p>
            <div class="bubble" id="nextStep"></div>
          </div>
          <footer>
            Need a refresher? Run <code>kubectl describe configmap web-ui-files -n configmap-lab</code> to see exactly what is mounted here.
          </footer>
        </main>
        <script src="./lab-data.js"></script>
        <script>
          const cfg = window.LAB_CONFIG || {};
          document.getElementById('headline').textContent = cfg.headline || 'No headline found';
          document.getElementById('blurb').textContent = cfg.blurb || '';
          document.getElementById('panelCopy').textContent = cfg.panel || '';
          document.getElementById('nextStep').textContent = cfg.callToAction || '';
        </script>
      </body>
    </html>
  lab-data.js: |
    window.LAB_CONFIG = {
      headline: "ConfigMaps mounted as volumes feel like instant content updates ✨",
      blurb: "The HTML and this friendly JavaScript object live inside a ConfigMap called web-ui-files. Kubernetes projects the ConfigMap into the pod, and nginx serves these files on every request.",
      panel: "Try editing the headline in manifests/03-volume-configmap/configmap.yaml and apply it again. Give the kubelet a few seconds to rotate the symlink, then refresh your browser.",
      callToAction: "Change me, apply, refresh!"
    };
